name: CI
on: 
  push:
    branches:
      - "main"

env:
  env_var: ${{ vars.G_SSH }}

jobs:
  Git_Pull:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html/green-light/
    steps:
      - name: add directory into safe 
        run: git config --global --add safe.directory /var/www/html/green-light 
      - name: pint
        run: echo $env_var
      - name: Taking Git Pull
        run: $env_var git pull

  Build:
    needs: Git_Pull
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html/green-light/
    steps:
      - name: Install dependencies
        run: npm install
      - name: pm2 reload
        run: pm2 reload 0
